### ISSUE TITLE
Throttle exception

### ISSUE THREAD

**Issue by imanghafoori1** [TheDragonCode/pretty-routes#53]
- Pretty Route Version: lastest
- Laravel Version: 8.x
- PHP Version: 8.1

### Description:
I get throttle exception after a little bit of playing with the UI. The project is pretty small with only a few routes.

**Comment by imanghafoori1** [comment]
it is show on a toast, dialog box. something ajaxy.

**Comment by andrey-helldar** [comment]
Delete the `storage/logs/laravel.log` file, then open the page. When you see an error, the file `storage/logs/laravel.log` will be created.

Attach the stack trace from the message to the message.

Without a mistake, I can't help you.

Also, additional information may be needed, but I can only say about it after reading the stack trace.

Problem not found in my routes:

![image](https://user-images.githubusercontent.com/10347617/160712537-f8b3032e-7d7b-47b8-b6ad-8d6d7a440fa1.png)

**Comment by andrey-helldar** [comment]
For example, 1233 routes. Problem not found.

![image](https://user-images.githubusercontent.com/10347617/161265687-09ce7b42-5434-4dd8-bb7f-b9052ee40a91.png)

**Comment by imanghafoori1** [comment]
Let me add that we use octane server

**Comment by andrey-helldar** [comment]
Native (`php artisan serve`):

![image](https://user-images.githubusercontent.com/10347617/161311688-5b129b3b-6a60-44a2-822c-eb75ceaa453d.png)

Octane + Sail:

![image](https://user-images.githubusercontent.com/10347617/161324358-9d72bfae-0e6a-4c3c-8d8f-6f04273aa11d.png)

Please send the error stack trace.

**Comment by imanghafoori1** [comment]
![Screenshot from 2022-04-01 23-36-26](https://user-images.githubusercontent.com/6961695/161326480-664b423d-629b-4b2d-a9b3-e2c670205039.png)

**Comment by imanghafoori1** [comment]
{
  "message": "Too Many Attempts.",
  "exception": "Illuminate\\Http\\Exceptions\\ThrottleRequestsException",
  "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
  "line": 200,
  "trace": [
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
      "line": 121,
      "function": "buildException",
      "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
      "line": 63,
      "function": "handleRequest",
      "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 103,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 723,
      "function": "then",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 698,
      "function": "runRouteWithinStack",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 662,
      "function": "runRoute",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 651,
      "function": "dispatchToRoute",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 167,
      "function": "dispatch",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 128,
      "function": "Illuminate\\Foundation\\Http\\{closure}",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
      "line": 21,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php",
      "line": 31,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
      "line": 21,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php",
      "line": 40,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
      "line": 27,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/fruitcake/laravel-cors/src/HandleCors.php",
      "line": 38,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Fruitcake\\Cors\\HandleCors",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php",
      "line": 39,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Http\\Middleware\\TrustProxies",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 103,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 142,
      "function": "then",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 111,
      "function": "sendRequestThroughRouter",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/octane/src/ApplicationGateway.php",
      "line": 36,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/octane/src/Worker.php",
      "line": 92,
      "function": "handle",
      "class": "Laravel\\Octane\\ApplicationGateway",
      "type": "->"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/octane/bin/swoole-server",
      "line": 117,
      "function": "handle",
      "class": "Laravel\\Octane\\Worker",
      "type": "->"
    },
    {
      "function": "{closure}"
    },
    {
      "file": "/var/www/vandar/vms-escrow/vendor/laravel/octane/bin/swoole-server",
      "line": 163,
      "function": "start",
      "class": "Swoole\\Server",
      "type": "->"
    }
  ]
}

**Comment by andrey-helldar** [comment]
I have read the stack trace. Octane has nothing to do with it.

What is the maximum number of requests per minute configured in your application? Namely, throttling.

It is he who drops the requests.
