### ISSUE TITLE
How to use it with Laravel 11?

### ISSUE THREAD

**Issue by uwla** [TheDragonCode/pretty-routes#74]
- Pretty Route Version: latest
- Laravel Version: 11
- PHP Version: 8.4

### Description:

The instructions provided by the README:

```
In your bootstrap/app.php file add a line above $app->register(App\Providers\RouteServiceProvider::class):

if (env('APP_ENV') !== 'production') {
    $app->register(\PrettyRoutes\ServiceProvider::class);
    $app->configure('pretty-routes');
}
```

Do not apply to Laravel 11 because `$app` is not defined and it is not possible to call `app()`.

### Steps To Reproduce:

Launch Laravel 11 project and install this package.

By the way, thanks for the project!

**Comment by andrey-helldar** [comment]
1. `composer require dragon-code/pretty-routes --dev`
2. Start the `php artisan serve` or nginx or Laravel Sail
3. Open the http://127.0.0.1:8000/routes page (or your domain name from the `APP_URL` parameter)

**Comment by andrey-helldar** [comment]
It's simple:

- `dragon-code/pretty-routes` requires `dragon-code/support` to be installed
- `dragon-code/support` requires the `bcmath` extension for PHP
- `bcmath` extension is not installed for your PHP

```bash
dragon-code/pretty-routes 3.4.0 requires dragon-code/support ^5.6 || ^6.1
dragon-code/support[v6.1.0, ..., 6.15.0] require ext-bcmath * -> it is missing from your system. Install or enable PHP's bcmath extension.
```

You must either install it, or run a command with the option to ignore it:

```bash
sudo apt install php8.4-bcmath
```
// or
```bash
composer require dragon-code/pretty-routes --dev --ignore-platform-req=ext-bcmath
```
