### ISSUE TITLE
Is it possible to customize UI? 

### ISSUE THREAD

**Issue by uwla** [TheDragonCode/pretty-routes#75]
Is it possible to customize the UI with CSS?

I'd like to make a very simple customization, which is to set `whitespace: nowrap` for `td`.

**Comment by andrey-helldar** [comment]
The current version of the package does not allow for customization of styles. Vuetify 2 styles are used for rendering.

https://github.com/TheDragonCode/pretty-routes/blob/main/resources/views/styles.blade.php

**Comment by uwla** [comment]
Ok, thanks.

I'll propose when I have time.
I remember there is a way to publish vendor files to resources/, so the user could tweak them there.
